id = "bind"
name = "Bind"
description = "Bind DNS configuration language support"
version = "0.1.0"
schema_version = 1
authors = ["Brandon Froehlich <bfroehlich@ferrilli.com>"]
repository = "https://github.com/bf-ferrilli/tree-sitter-bind"

[grammars.bind]
repository = "https://github.com/bf-ferrilli/tree-sitter-bind"
commit = "67c1b6f337036333cd09317edf33ae0fb0159bbe"
