id = "bind"
name = "BIND"
description = "BIND DNS configuration language support"
version = "0.4.0"
schema_version = 1
authors = ["Brandon Froehlich <bfroehlich@ferrilli.com>"]
repository = "https://github.com/bf-ferrilli/tree-sitter-bind"

[grammars.bind]
repository = "https://github.com/bf-ferrilli/tree-sitter-bind"
rev = "4387a2abd865d31dadf845086d015bfc268f8811"
