/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 8
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__item_token1 = 1,
  sym_comment = 2,
  sym_directive = 3,
  sym_record = 4,
  sym_source_file = 5,
  sym__item = 6,
  aux_sym_source_file_repeat1 = 7,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__item_token1] = "_item_token1",
  [sym_comment] = "comment",
  [sym_directive] = "directive",
  [sym_record] = "record",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__item_token1] = aux_sym__item_token1,
  [sym_comment] = sym_comment,
  [sym_directive] = sym_directive,
  [sym_record] = sym_record,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__item_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (eof) ADVANCE(26);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == ';') ADVANCE(28);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(31);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        'A', 3,
        'C', 14,
        'H', 10,
        'I', 12,
        'M', 23,
        'N', 18,
        'P', 19,
        'S', 16,
        'T', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        'A', 3,
        'C', 14,
        'H', 10,
        'M', 23,
        'N', 18,
        'P', 19,
        'S', 16,
        'T', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'A') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        'A', 106,
        'C', 116,
        'H', 112,
        'I', 114,
        'M', 125,
        'N', 120,
        'P', 121,
        'S', 118,
        'T', 124,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(128);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'F') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'I') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'M') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'N') ADVANCE(5);
      END_STATE();
    case 15:
      if (lookahead == 'O') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'O') ADVANCE(6);
      if (lookahead == 'R') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'S') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'T') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'T') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'V') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'X') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 'X') ADVANCE(24);
      END_STATE();
    case 24:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      END_STATE();
    case 25:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__item_token1);
      ADVANCE_MAP(
        '\n', 1,
        '\r', 29,
        'A', 34,
        'C', 53,
        'H', 50,
        'I', 54,
        'M', 62,
        'N', 58,
        'P', 59,
        'S', 56,
        'T', 63,
        '\t', 27,
        0x0b, 27,
        '\f', 27,
        ' ', 27,
      );
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '\r') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__item_token1);
      ADVANCE_MAP(
        '\n', 1,
        'A', 36,
        'C', 82,
        'H', 76,
        'I', 84,
        'M', 100,
        'N', 92,
        'P', 94,
        'S', 87,
        'T', 101,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__item_token1);
      ADVANCE_MAP(
        '\n', 4,
        'A', 37,
        'C', 83,
        'H', 77,
        'I', 85,
        'M', 103,
        'N', 93,
        'P', 95,
        'S', 88,
        'T', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(129);
      if (lookahead == '\r') ADVANCE(38);
      if (lookahead == 'A') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(129);
      if (lookahead == '\r') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(129);
      if (lookahead == 'A') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(129);
      if (lookahead == 'A') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(129);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(129);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__item_token1);
      ADVANCE_MAP(
        '\n', 2,
        '\r', 42,
        'A', 34,
        'C', 53,
        'H', 50,
        'M', 62,
        'N', 58,
        'P', 59,
        'S', 56,
        'T', 63,
        '\t', 40,
        0x0b, 40,
        '\f', 40,
        ' ', 40,
      );
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '\r') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__item_token1);
      ADVANCE_MAP(
        '\n', 2,
        'A', 36,
        'C', 82,
        'H', 76,
        'M', 100,
        'N', 92,
        'P', 94,
        'S', 87,
        'T', 101,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\n') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'A') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'A') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'A') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'E') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'F') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'I') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'M') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'N') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'N') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'N') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'O') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'O') ADVANCE(46);
      if (lookahead == 'R') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'R') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'S') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'T') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'T') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'V') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'X') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == 'X') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == ';') ADVANCE(28);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(31);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'A') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'A') ADVANCE(79);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'A') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'A') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'A') ADVANCE(71);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'A') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'E') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'E') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'F') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'F') ADVANCE(89);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'I') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'I') ADVANCE(81);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'M') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'M') ADVANCE(73);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'N') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'N') ADVANCE(75);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'N') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'N') ADVANCE(67);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'N') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'N') ADVANCE(44);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'O') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'O') ADVANCE(68);
      if (lookahead == 'R') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'O') ADVANCE(71);
      if (lookahead == 'R') ADVANCE(99);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'O') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'R') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'R') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'S') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'S') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'T') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'T') ADVANCE(91);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'T') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'T') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'V') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'V') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'X') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'X') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'X') ADVANCE(97);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == 'X') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym__item_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'A') ADVANCE(109);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0) ADVANCE(128);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'A') ADVANCE(113);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'A') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'A') ADVANCE(108);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'E') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'F') ADVANCE(117);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'I') ADVANCE(115);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'M') ADVANCE(110);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'N') ADVANCE(127);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'N') ADVANCE(111);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'N') ADVANCE(107);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'O') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'O') ADVANCE(108);
      if (lookahead == 'R') ADVANCE(123);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'R') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'S') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'T') ADVANCE(119);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'T') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'V') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'X') ADVANCE(122);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == 'X') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_directive);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0) ADVANCE(128);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_directive);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(128);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_record);
      if (lookahead == '\n') ADVANCE(129);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0) ADVANCE(130);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_record);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(130);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__item_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_directive] = ACTIONS(1),
    [sym_record] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(4),
    [sym__item] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__item_token1] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [sym_directive] = ACTIONS(5),
    [sym_record] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [aux_sym__item_token1] = ACTIONS(9),
    [sym_comment] = ACTIONS(9),
    [sym_directive] = ACTIONS(9),
    [sym_record] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [aux_sym__item_token1] = ACTIONS(13),
    [sym_comment] = ACTIONS(13),
    [sym_directive] = ACTIONS(13),
    [sym_record] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(16), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [16] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bind(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bind",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
